modLoader="javafml"
loaderVersion="[39,)"
issueTrackerURL="https://github.com/owmii/powah/issues"
license="LGPLv3"

[[mods]]
modId="powah"
version="${file.jarVersion}"
displayName="Powah"
displayURL="https://www.curseforge.com/minecraft/mc-mods/powah"
authors="owmii"
description='''
Various ways to generate, store and transmit FE power.
'''

[[dependencies.powah]]
    modId="lollipop"
    mandatory=true
    versionRange="[3.2.9,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.powah]]
    modId="forge"
    mandatory=true
    versionRange="[39.0.10,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
# XDW has added MC Dependency for 1.18
# This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"
